version: 2
updates:
- package-ecosystem: pip
  directory: "/back"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
- package-ecosystem: npm
  directory: "/front"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
