version: "3"

services:
  # API
  homeware-lan-back-api:
    image: ghcr.io/kikeelectronico/homewarelan-back
    restart: always
    hostname: backend
    command: "gunicorn -w 1 -b 0.0.0.0:5001 homewareAPI:app"
    environment:
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
      - HOMEWARE_USER=${HOMEWARE_USER}
      - HOMEWARE_PASSWORD=${HOMEWARE_PASSWORD}
      - HOMEWARE_DOMAIN=${DOMAIN}
    expose:
      - "5001"
    depends_on:
      - redis
      - mosquitto
    volumes:
      - homeware-logs:/app/logs
      - homeware-files:/app/files

  # tasks
  homeware-lan-back-tasks:
    image: ghcr.io/kikeelectronico/homewarelan-back
    restart: always
    hostname: backend-tasks
    command: "python homewareTasks.py"
    environment:
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    depends_on:
      - redis
      - mosquitto
      - homeware-lan-back-api
    volumes:
      - homeware-logs:/app/logs
      - homeware-files:/app/files

  # MQTT
  homeware-lan-back-mqtt:
    image: ghcr.io/kikeelectronico/homewarelan-back
    restart: always
    hostname: backend-mqtt
    command: "python homewareMQTT.py"
    environment:
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    depends_on:
      - redis
      - mosquitto
      - homeware-lan-back-api
    volumes:
      - homeware-logs:/app/logs
      - homeware-files:/app/files

  # redis
  redis:
    image: redis:6.0
    restart: always
    hostname: redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data

  # mosquitto
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    hostname: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"
    volumes:
      - ./configuration_templates/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./configuration_templates/mosquitto_passwd:/mosquitto/config/passwd:ro
      - mosquitto-data:/mosquitto/data

  # nginx proxy for API & FE
  nginx:
    image: ghcr.io/kikeelectronico/homewarelan-nginx
    restart: always
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    depends_on:
      - homeware-lan-back-api
      - nginx-proxy

  # nginx reverse proxy
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # certificate helper
  letsencrypt:
    image: alexanderkrause/rpi-letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro


volumes:
  html:
  certs:
  vhostd:
  mosquitto-data:
  redis-data:
  homeware-logs:
  homeware-files: