# Site settings
title: Homeware
description: A full ecosystem for Google Home integration using Raspberry Pi.
baseurl: "/Homeware-LAN" # the subpath of your site, e.g. /blog
url: "https://kikeelectronico.github.io/Homeware-LAN/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner Section
hero: pages/home/warm-and-cozy.jpg
hero-title: Welcome to Homeware
hero-description: A full ecosystem for Google Home integration using Raspberry Pi.

# Author - Creator
author-name: Enrique
author-image: enrique.jpeg
about-author: .
author-email: hola at rinconingenieril.es
author-twitter: https://twitter.com/kikeelectronico

# Other Authors - here you can add Other authors. For example Natali_Braxton
# authors:
#   Natali_Braxton:
#     author-name: Natali Braxton
#     author-image: 111.jpg
#     about-author: My name is Natali Braxton. I love walking, I play the guitar in my spare time. And also write articles about different technologies.
#     author-email: natali.example@gmail.com
#     author-twitter: https://twitter.com/
#     author-facebook: https://twitter.com/
#     author-instagram: https://www.instagram.com/
#     author-pinterest: https://pinterest.com/

# Social Media Links (Links are located in hero and footer)
# twitter: https://twitter.com/
# facebook: https://facebook.com/
# google-plus: https://plus.google.com/
# instagram: https://www.instagram.com/
# pinterest: https://pinterest.com/
# youtube: https://www.youtube.com/

# Contact Form Settings
# contact-subtitle: Pok pok listicle meggings, gluten-free deep v you probably haven't heard of them taxidermy iPhone gentrify seitan. Kogi cornhole enamel. # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
